from datetime import datetime
from sqlalchemy import Column, String, DateTime, Boolean
from sqlalchemy_utils import UUIDType
from short.databases import Base


class URLS(Base):
    __tablename__ = 'urls'

    id = Column(UUIDType, primary_key=True)
    original_url = Column(String(400), nullable=False)
    short_url = Column(String(200), nullable=False, unique=True)
    created_at = Column(DateTime, default=datetime.utcnow())
    is_autogenerated = Column(Boolean, default=True)

